english/urls.py
from django.urls import path

from . import views
app_name = 'english'
urlpatterns = [
    path('', views.index, name='index'),
    path('correction', views.correction, name='correction'),
    path('payment_success_backend', views.payment_success_backend, name='payment_success_backend'),
    path('payment_result', views.payment_result, name='payment_result'),
    path('terms_of_service', views.terms_of_service, name='terms_of_service'),
    path('profile', views.profile, name='profile'),
    path('market', views.market, name='market'),
    path('post_answer', views.post_answer, name='post_answer'),
    path('winner', views.winner, name='winner'),
    path('get_coins', views.get_coins, name='get_coins'),
    path('read_notifications', views.read_notifications, name='read_notifications'),
    path('like_question', views.like_question, name='like_question'),
]

teacher/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('', include('english.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('djga/', include('google_analytics.urls')),
]

english/forms.py
from django import forms
from .models import Essay, Answer
from allauth.account.forms import LoginForm, SignupForm, ResetPasswordForm

class EssayForm(forms.ModelForm):
    class Meta:
        model = Essay
        fields = ['essay_text']

        widgets = {
            'essay_text': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Write your question or essay here ... ', 'rows':8}),
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['answer_text']

        widgets = {
            'answer_text': forms.Textarea(attrs={'class':'form-control', 'id':'exampleBlogPost', 'rows':6}),
        }

class CustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget = forms.TextInput(attrs={'type': 'email', 'placeholder': 'Email ... ', 'class': 'form-control'})
        self.fields['password'].widget = forms.PasswordInput(attrs={'placeholder': 'Password ... ', 'class': 'form-control'})

class CustomSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super(CustomSignupForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.TextInput(attrs={'type': 'email', 'placeholder': 'Email ... ', 'class': 'form-control'})
        self.fields['password1'].widget = forms.PasswordInput(attrs={'placeholder': 'Password ... ', 'class': 'form-control'})

class CustomResetPasswordForm(ResetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(CustomResetPasswordForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.TextInput(attrs={'type': 'email', 'placeholder': 'Email ... ', 'class': 'form-control'})

english/views.py
import json, requests, re

from django.http import JsonResponse
from django.urls import reverse
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.defaultfilters import truncatechars
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .forms import EssayForm, AnswerForm, CustomLoginForm
from .models import Essay, Answer, Profile, UserAction, LikeQuestion
from allauth.account.signals import user_signed_up
from django.dispatch import receiver
from datetime import datetime, timezone
from django.db.models import F
import math

#notification system
from notifications.models import Notification

flags = {'math': 'MATH', 'no': 'Natural Science', 'so': 'Social Science', 'other': 'Other', 'en-US' : 'US', 'es' : 'ES', 'fr' : 'FR', 'de' : 'DE', 'it' : 'IT', 'pt' : 'PT', 'sv' : 'SE'}
subjects = {'math': 'Mathematics', 'no': 'Natural Science', 'so': 'Social Science', 'other': 'Other', 'en-US' : 'English', 'es' : 'Español', 'fr' : 'Français', 'de' : 'Deutsch', 'it' : 'Italiano', 'pt' : 'Português', 'sv' : 'Svenska'}

from allauth.account.signals import user_logged_in, user_logged_out, user_signed_up, password_changed, password_reset, email_confirmed, user_signed_up

@receiver(user_logged_in)
def user_logged_in(sender, request, user, **kwargs):
    user_action = UserAction.objects.create(user=user, action="user_logged_in")

@receiver(user_logged_out)
def user_logged_out(sender, request, user, **kwargs):
    user_action = UserAction.objects.create(user=user, action="user_logged_out")

@receiver(user_signed_up)
def user_signed_up(sender, request, user, **kwargs):
    user_action = UserAction.objects.create(user=user, action="user_signed_up")
    profile = Profile.objects.create(user=user)

@receiver(password_changed)
def password_changed(sender, request, user, **kwargs):
    user_action = UserAction.objects.create(user=user, action="password_changed")

@receiver(password_reset)
def password_reset(sender, request, user, **kwargs):
    user_action = UserAction.objects.create(user=user, action="password_reset")

@receiver(email_confirmed)
def email_confirmed(sender, request, user, **kwargs):
    user_action = UserAction.objects.create(user=user, action="email_confirmed")

def get_notifications(request):
    user = request.user
    if request.user.is_anonymous:
        return [], False
    else:
        notifications = Notification.objects.filter(recipient=user).order_by('-timestamp')
        has_unread_notifications = False
        #remove items where the actor = recipient
        notifications = [n for n in notifications if not n.actor == request.user]
        for notification in notifications:
            notification.time_ago = get_date(notification.timestamp)
            if notification.unread == True:
                has_unread_notifications = True

        return notifications, has_unread_notifications

def get_date(timestamp):
        difference = datetime.now(timezone.utc) - timestamp
        minutes = int(round(difference.total_seconds() / 60))

        if minutes < 60:
            if minutes == 1:
                return "1 minute ago"
            else:
                return str(minutes) + " minutes ago"
        elif minutes < 1440:
            hours = math.floor(minutes/60)
            if hours == 1:
                return "1 hour ago"
            else:
                return str(hours) + " hours ago"
        elif minutes < 43200:
            days = math.floor(minutes/1440)
            if days == 1:
                return "1 day ago"
            else:
                return str(days) + " days ago"
        elif minutes < 525600:
            months = math.floor(minutes/43200)
            if months == 1:
                return "1 month ago"
            else:
                return str(months) + " months ago"
        elif minutes >= 525600:
            years = math.floor(minutes/525600)
            if years == 1:
                return "1 year ago"
            else:
                return str(years) + " years ago"

def cleanhtml(raw_html):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', raw_html)
    return cleantext

def config_errors(original, errors):
    parts = []
    start = 0

    errors = sorted(errors, key = lambda i: i['offset'])
    error_types = {'total' : 0, 'style' : 0, 'grammar' : 0, 'typographical' : 0, 'misspelling' : 0, 'formatting' : 0, 'duplication' : 0, 'whitespace': 0, 'register': 0, 'uncategorized': 0, 'non_conformance': 0}

    for error in errors:
        # count the number of errors
        error_types[error['type'].replace('-', '_')] += 1
        error_types['total'] += 1
        corrections = error['corrections']
        correction_text = ""
        for i in range(len(corrections)):
            #If there is only 1 correction, don't surround it with parenthesis
            placeholder = corrections[i]
            if len(corrections) == 1:
                correction_text = placeholder
            else:
                #If there are several, separate them with commas, use the variable i to set a limit on how many corrections should  be displayed
                if i == 0:
                    correction_text = "(" + placeholder + ", "
                elif i != len(corrections) - 1 and i != 2:
                    correction_text = correction_text + placeholder + ', '
                elif i == len(corrections) - 1 or i == 2:
                    correction_text = correction_text + placeholder + ")"
                    break
        if error['message'] != '':
            popover_header = error['message']
        else:
            popover_header = error['type']
        the_string = "<u><a href='#' data-toggle='popover' title='{}' data-placement='top'><mark class='error'>".format(popover_header)
        parts += original[start:error['offset']], the_string
        start = (error['offset'])
        if correction_text != "":
            correction_mark = "<mark class='correction'>{}</mark>".format(correction_text)
        else:
            correction_mark = ""
        parts += original[start:(error['offset']+error['length'])], "</mark></a></u>" + correction_mark
        start = (error['offset']+error['length'])
    parts += original[start:],
    return ''.join(parts), error_types


def read_notifications(request):
    #Update all notifications of user to unread=False, this happens when the user reads their notifications
    data = {'user': request.user}
    if request.method == "GET":
        username = request.GET.get('username')
        if username == request.user.username:
            notifications = Notification.objects.filter(recipient=request.user, unread=True).update(unread=False)
    return JsonResponse(data)

def like_question(request):
    data = {'username': request.user.username}
    if request.method == "GET":
        username = request.GET.get('username')
        essay = Essay.objects.filter(essay_id=request.GET.get('essay')).first()
        if essay:
            if username == request.user.username:
                try:
                    like = LikeQuestion.objects.get(user=request.user, essay=essay)
                except:
                    like = False
                if not like:
                    LikeQuestion.objects.create(user=request.user, essay=essay)
                    essay.upvotes=essay.upvotes+1
                    essay.save()

    return JsonResponse(data)

def index(request):

    notifications, has_unread_notifications = get_notifications(request)

    try:
        lang_id = request.GET['lang_id']
        selected_lang = {'flag' : flags[lang_id], 'lang' : subjects[lang_id], 'lang_id' : lang_id}
    except:
        selected_lang = {'flag' : 'none', 'lang' : 'none', 'lang_id': 'none'}

    if request.method == 'POST':
        if request.user.is_anonymous is True:
            return(redirect('/accounts/signup'))
        bounty = request.POST.get('bounty')
        lang_id = selected_lang['lang_id']
        form = EssayForm(request.POST)
        if lang_id == "none":
            return render(request, 'english/index.html', {'form': form, 'selected_lang': selected_lang, 'page_error': 'select_subject', 'notifications': notifications, 'has_unread_notifications': has_unread_notifications})
        elif bounty.isnumeric() is False:
            return render(request, 'english/index.html', {'form': form, 'selected_lang': selected_lang, 'page_error': 'enter_bounty', 'notifications': notifications, 'has_unread_notifications': has_unread_notifications})
        elif int(bounty) < 1:
            return render(request, 'english/index.html', {'form': form, 'selected_lang': selected_lang, 'page_error': 'bounty_too_small', 'notifications': notifications, 'has_unread_notifications': has_unread_notifications})
        else:
            if form.is_valid():
                essay = form.save()
                essay.is_valid = False
                essay.author = request.user
                essay.essay_text = cleanhtml(essay.essay_text)
                essay.characters = len(essay.essay_text)
                essay.language = lang_id
                essay.subject = subjects[lang_id]
                essay.bounty = bounty
                if essay.title == "":
                    essay.title = truncatechars(essay.essay_text, 32)
                else:
                    essay.title = cleanhtml(essay.title)

                author_coins = essay.author.profile.coins
                if int(bounty) > author_coins:
                    return render(request, 'english/index.html', {'form': form, 'selected_lang': selected_lang, 'page_error': 'insufficient_coins', 'notifications': notifications, 'has_unread_notifications': has_unread_notifications})
                else:
                    essay.author.profile.coins -= int(bounty)

                essay.author.profile.save()
                essay.is_valid = True
                essay.save()

english/templates/english/checkout.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <title>ease-a</title>

    <link href="{% static 'english/assets/css/bootstrap.css' %}" rel="stylesheet" />
	<link href="{% static 'english/assets/css/coming-sssoon.css' %}" rel="stylesheet" />

    <!--     Fonts     -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>

	{% load google_analytics_tags %}
	<div style="display:none">
	    <img src="{% google_analytics %}" width="0" height="0" />
	</div>
	<link href='https://fonts.googleapis.com/css?family=Handlee' rel='stylesheet'>

	<!-- Hotjar Tracking Code for www.ease-a.com -->
	<script>
	    (function(h,o,t,j,a,r){
	        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
	        h._hjSettings={hjid:1960796,hjsv:6};
	        a=o.getElementsByTagName('head')[0];
	        r=o.createElement('script');r.async=1;
	        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
	        a.appendChild(r);
	    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
	</script>
</head>

<body>
<!-- Brand and toggle get grouped for better mobile display -->
<!--
<nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
-->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <!--
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src="{% static 'english/assets/images/flags/US.png' %}"/>
                Login
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="#"><img src="{% static 'english/assets/images/flags/DE.png' %}"/> Deutsch</a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/GB.png' %}"/> English(UK)</a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/FR.png' %}"/> Français</a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/RO.png' %}"/> Română</a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/IT.png' %}"/> Italiano</a></li>

                <li class="divider"></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/ES.png' %}"/> Español <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/BR.png' %}"/> Português <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/JP.png' %}"/> 日本語 <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/TR.png' %}"/> Türkçe <span class="label label-default">soon</span></a></li>

              </ul>
        </li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="#">
                    <i class="fa fa-facebook-square"></i>
                    Like
                </a>
            </li>
             <li>
                <a href="#">
                    <i class="fa fa-twitter"></i>
                    Tweet
                </a>
            </li>
             <li>
                <a href="#">
                    <i class="fa fa-gittip"></i>
                    Gittip
                </a>
            </li>
       </ul>

    </div><!-- /.navbar-collapse -->
    <!-- -->
  </div><!-- /.container -->
</nav>
<div class="main" style="background-image: url('{% static 'english/assets/images/writer_wallpaper.jpg' %}')">

<!--    Change the image source '/images/restaurant.jpg')" with your favourite image.     -->

<div class="cover black" data-color="black"></div>

<!--   You can change the black color for the filter with those colors: blue, green, red, orange       -->

    <div class="container">
        <h1 class="logo">
            Payment Checkout
        </h1>
        <div class="content">
            <div class="subscribe">
                <h5 class="info-text">
						Your essay will be corrected and sent to you within <strong>24 hours</strong> of completed payment. <br /><br />
						Your essay has <u>{{ words }} words</u>.
                </h5>
                <div class="row">
                    <div class="col-md-8 col-md-offset-0 col-sm6-4 col-sm-offset-1 ">
						<div class="paper">
						    <div class="paper-content">
						        <textarea readonly>{{ essay.essay_text }}</textarea>
						    </div>
						</div>
					</div>
					<div class="col-md-4 col-md-offset-0 col-sm6-4 col-sm-offset-1 payment-choices-box">
						<h5 class="info-text"><strong>Choose your payment method</strong></h5>
                        <!-- Set up a container element for the button -->
                        <div id="paypal-button-container"></div>
                        <!-- Include the PayPal JavaScript SDK -->
                        <script src="https://www.paypal.com/sdk/js?client-id=AcCS6uqyTktqYnZnyGOo_uz71Qk0rLsm1NHJ0FsMHqaiGIPnXcR83syGD2OAgBpPPhhWKSQrYcf9OAl_&currency=EUR"></script>

                        <script>

                            function getCookie(name) {
                                let cookieValue = null;
                                if (document.cookie && document.cookie !== '') {
                                    const cookies = document.cookie.split(';');
                                    for (let i = 0; i < cookies.length; i++) {
                                        const cookie = cookies[i].trim();
                                        // Does this cookie string begin with the name we want?
                                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                            break;
                                        }
                                    }
                                }
                                return cookieValue;
                            }
                            const csrftoken = getCookie('csrftoken');

                            var total = '{{ essay.price }}'
                            var essay_id = '{{ essay.essay_id }}'

                            function completePayment(){
                                var url = "{% url 'english:payment_success_backend' %}"

                                fetch(url, {
                                    method: 'POST',
                                    headers:{
                                        'Content-type':'appliction/json',
                                        'X-CSRFToken': csrftoken,
                                    },
                                    body:JSON.stringify({'essay_id': essay_id})
                                })
                            }

                            // Render the PayPal button into #paypal-button-container
                            paypal.Buttons({

                                // Set up the transaction
                                createOrder: function(data, actions) {
                                    return actions.order.create({
                                        purchase_units: [{
                                            amount: {
                                                value: total
                                            }
                                        }]
                                    });
                                },

                                // Finalize the transaction
                                onApprove: function(data, actions) {
                                    return actions.order.capture().then(function(details) {
                                        // Show a success message to the buyer
                                        completePayment()
                                        window.location.href = "{% url 'english:payment_result' %}?essay_id={{ essay.essay_id }}";
                                    });
                                }


                            }).render('#paypal-button-container');
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
   <script src="{% static 'english/assets/js/jquery-1.10.2.js' %}" type="text/javascript"></script>
   <script src="{% static 'english/assets/js/bootstrap.min.js' %}" type="text/javascript"></script>

</html>

english/templates/english/payment.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <title>ease-a</title>

    <link href="{% static 'english/assets/css/bootstrap.css' %}" rel="stylesheet" />
	<link href="{% static 'english/assets/css/coming-sssoon.css' %}" rel="stylesheet" />

    <!--     Fonts     -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>

	{% load google_analytics_tags %}
	<div style="display:none">
	    <img src="{% google_analytics %}" width="0" height="0" />
	</div>
</head>

<body>
<!-- Brand and toggle get grouped for better mobile display -->
<!--
<nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
-->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <!--
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src="{% static 'english/assets/images/flags/US.png' %}"/>
                Login
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="#"><img src="{% static 'english/assets/images/flags/DE.png' %}"/> Deutsch</a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/GB.png' %}"/> English(UK)</a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/FR.png' %}"/> Français</a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/RO.png' %}"/> Română</a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/IT.png' %}"/> Italiano</a></li>

                <li class="divider"></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/ES.png' %}"/> Español <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/BR.png' %}"/> Português <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/JP.png' %}"/> 日本語 <span class="label label-default">soon</span></a></li>
                <li><a href="#"><img src="{% static 'english/assets/images/flags/TR.png' %}"/> Türkçe <span class="label label-default">soon</span></a></li>

              </ul>
        </li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="#">
                    <i class="fa fa-facebook-square"></i>
                    Like
                </a>
            </li>
             <li>
                <a href="#">
                    <i class="fa fa-twitter"></i>
                    Tweet
                </a>
            </li>
             <li>
                <a href="#">
                    <i class="fa fa-gittip"></i>
                    Gittip
                </a>
            </li>
       </ul>

    </div><!-- /.navbar-collapse -->
    <!-- -->
  </div><!-- /.container -->
</nav>
<div class="main" style="background-image: url('{% static 'english/assets/images/writer_wallpaper.jpg' %}')">

<!--    Change the image source '/images/restaurant.jpg')" with your favourite image.     -->


<div class="cover black" data-color="black"></div>

<!--   You can change the black color for the filter with those colors: blue, green, red, orange       -->

    <div class="container">
        <h1 class="logo">
            Payment Checkout
        </h1>
        <div class="content">
            <div class="subscribe">
                <h5 class="info-text">
					<i>
						Your essay will start be processed with your payment, <br />
						and will be sent back to your email within <strong>24 hours</strong>!
                    </i>
                </h5>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 col-sm6-6 col-sm-offset-3 ">

                        <!-- Set up a container element for the button -->
                        <div id="paypal-button-container"></div>
                        <!-- Include the PayPal JavaScript SDK -->
                        <script src="https://www.paypal.com/sdk/js?client-id=AcCS6uqyTktqYnZnyGOo_uz71Qk0rLsm1NHJ0FsMHqaiGIPnXcR83syGD2OAgBpPPhhWKSQrYcf9OAl_&currency=EUR"></script>

                        <script>

                            function getCookie(name) {
                                let cookieValue = null;
                                if (document.cookie && document.cookie !== '') {
                                    const cookies = document.cookie.split(';');
                                    for (let i = 0; i < cookies.length; i++) {
                                        const cookie = cookies[i].trim();
                                        // Does this cookie string begin with the name we want?
                                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                            break;
                                        }
                                    }
                                }
                                return cookieValue;
                            }
                            const csrftoken = getCookie('csrftoken');

                            var total = '{{ essay.price }}'
                            var essay_id = '{{ essay.essay_id }}'

                            function completePayment(){
                                var url = "{% url 'english:payment_success_backend' %}"

                                fetch(url, {
                                    method: 'POST',
                                    headers:{
                                        'Content-type':'appliction/json',
                                        'X-CSRFToken': csrftoken,
                                    },
                                    body:JSON.stringify({'essay_id': essay_id})
                                })
                            }

                            // Render the PayPal button into #paypal-button-container
                            paypal.Buttons({

                                // Set up the transaction
                                createOrder: function(data, actions) {
                                    return actions.order.create({
                                        purchase_units: [{
                                            amount: {
                                                value: total
                                            }
                                        }]
                                    });
                                },

                                // Finalize the transaction
                                onApprove: function(data, actions) {
                                    return actions.order.capture().then(function(details) {
                                        // Show a success message to the buyer
                                        completePayment()
                                        window.location.href = "{% url 'english:payment_result' essay.essay_id %}";
                                    });
                                }


                            }).render('#paypal-button-container');
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
   <script src="{% static 'english/assets/js/jquery-1.10.2.js' %}" type="text/javascript"></script>
   <script src="{% static 'english/assets/js/bootstrap.min.js' %}" type="text/javascript"></script>

</html>

english/templates/english/payment_fail.html
<h1> Payment Failed </h1>

Return to the <a href="{% url 'english:index' %}">home page</a> and try again.